version: '3.8'

services:
  postgres_db:
    image: postgres
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - $PWD/server.crt:/var/lib/postgresql/server.crt
      - $PWD/server.key:/var/lib/postgresql/server.key
      - $PWD/db-scripts:/docker-entrypoint-initdb.d/
    
    
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"


  read_service:
    # container_name: read_service
    build: read-service
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://discovery:8761/eureka"}}}}'
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/test_db?sslmode=require&ssl=true&sslrootcert=/var/lib/docker/volumes/certificate_volumes/server.crt     
    ports:
      - "7003:7003"
    depends_on: 
      - postgres_db
      - discovery
    volumes: 
      - $PWD/server.crt:/var/lib/docker/volumes/certificate_volumes/server.crt

  write_service:
    # container_name: read_service
    build: write-service
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://discovery:8761/eureka"}}}}'
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/test_db?sslmode=require&ssl=true&sslrootcert=/var/lib/docker/volumes/certificate_volumes/server.crt    
    ports:
      - "6003:6003"
    depends_on: 
      - postgres_db
      - discovery
    volumes: 
      - $PWD/server.crt:/var/lib/docker/volumes/certificate_volumes/server.crt

  
  discovery:
    build: service-registry
    ports:
      - "8761:8761"


  gateway_service:
    build: service-gateway
    ports:
      - "8443:8443"
    depends_on: 
      - discovery
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://discovery:8761/eureka"}}}}'


  admin_service:
    build: backend-admin
    ports:
      - "1001:1001"
    depends_on: 
      - discovery
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://discovery:8761/eureka"}}}}'
  




# # networks: 
# #   awakelabs-networks:
# #     driver: bridge
